<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2xmngyo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2xmngyo/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2xmngyo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2xmngyo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2xmngyo\appProdProjectContainer([
    'container.build_hash' => '2xmngyo',
    'container.build_id' => '1291dbd5',
    'container.build_time' => 1611068311,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2xmngyo');
